name: "Build"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 8

      - name: Build
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          mvn package --no-transfer-progress --batch-mode --settings maven-settings-github.xml

      - name: Login to GHCR
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        if: github.ref == 'refs/heads/main'
        id: tag
        run: |
          TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Build and push sporingslogg Docker  image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/navikt/sporingslogg/sporingslogg-nais:${{ env.TAG }}

  deploy:
    name: "Deploy With Parameters"
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - envclass: q
            environment: q2
            maskinporten_enabled: false
            vault_serviceuser_folder: dev
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev_q2.yaml
          IMAGE: ghcr.io/navikt/sporingslogg/sporingslogg-nais:${{ needs.build.outputs.tag }}
          TEAM: pensjonsamhandling
          VAR: envclass=${{ matrix.envclass }},environment=${{ matrix.environment }},maskinporten_enabled=${{ matrix.maskinporten_enabled }},vault_serviceuser_folder=${{ matrix.vault_serviceuser_folder }}
