name: Bygg og deploy Q2

on:
  push:
    branches:
      - master
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/sporingslogg:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # JAVA
      - name: 'Java 18'
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: temurin

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build --stacktrace
          docker build --tag ${{ env.IMAGE }} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # DEPLOYER TIL NAIS Q2 team namespace
      - name: 'Deploy to NAIS q2'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev_q2.yaml
          IMAGE: ${{ env.IMAGE }}

      # OPPRETTER GIT TAG
      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/sporingslogg/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Deploy to NAIS Prod'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod.yaml
          IMAGE: ${{ env.IMAGE }}
