name: Deploy topics

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Deploy public-sporingslogg-loggmeldingMottatt-q2 to pensjonsamhandling namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/loggmeldingmottatt-q2.yaml

#      - name: 'Deploy public-sporingslogg-loggmeldingMottatt to pensjonsamhandling namespace'
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: nais/topics/loggmeldingMottatt.yaml